apiVersion: apps/v1
kind: Deployment
metadata:
  name: hms-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hms
  template:
    metadata:
      labels:
        app: hms
    spec:
      containers:
      - name: hms-container
        image: hms-app:latest
        imagePullPolicy: Never
        ports:
          - containerPort: 8085
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: hms-config
              key: SPRING_DATASOURCE_URL
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          valueFrom:
            configMapKeyRef: 
              name: hms-config
              key: SPRING_JPA_HIBERNATE_DDL_AUTO         
        - name: SPRING_JPA_SHOW_SQL
          valueFrom:
            configMapKeyRef:
              name: hms-config
              key: SPRING_JPA_SHOW_SQL
        - name: SPRING_JPA_DATABASE_PLATFORM
          valueFrom:
            configMapKeyRef: 
              name: hms-config
              key: SPRING_JPA_DATABASE_PLATFORM
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: hms-secret
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef: 
              name: hms-secret # Fixed indentation here (added 2 spaces)
              key: SPRING_DATASOURCE_PASSWORD 
